version: "3.8"

services:

  # DNSmasq - DNS and DHCP server
  dnsmasq:
    container_name: dnsmasq
    image: tschaffter/dnsmasq:2.85    
    volumes:
      - ./config/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./config/dnsmasq/cyber.uml.edu.conf:/etc/dnsmasq.d/cyber.uml.edu.conf:ro
    command: ["dnsmasq", "-k", "--server", "1.1.1.1", "--server", "1.0.0.1"]
    ports:
     - "53:53/udp"
     - "53:53/tcp"

    restart: unless-stopped