# Adapted from: https://tizutech.com/hardening-ssh-with-ansible/

- name: Secure SSH
  hosts: main_infra
  vars_files:
    - variables.yml
  become_user: root
  tasks:
  - name: Hardening sshd
    block:
      - name: Editing sshd config
        lineinfile:
          dest: "/etc/ssh/sshd_config"
          regexp:` "{{ item.regexp | default(omit) }}"
          line: "{{ item.line }}"
          state: "{{ item.state | default('present') }}"
          validate: "sshd -t -f %s"
        with_items:
          # Change protocol version to 2 to allow better cipher suites.
          - line: "Protocol 2"
          - line: "Protocol 1"
            state: "absent"
          
          # Removes RSAAuthentication which is deprecated.
          - line: "RSAAuthentication yes"
            state: "absent"
          
          # Changes SSH port
          - regexp: "^Port\ "
            line: "Port {{ ssh_port }}"
          
          # Sets PermitRootLogin to no. This disables direct root login via SSH.
          - regexp: "^PermitRootLogin\ "
            line: "PermitRootLogin no"
          
          # Sets PasswordAuthentication to no. This only allows key based logins.
          - regexp: "^PasswordAuthentication\ "
            line: "PasswordAuthentication no"
          
          # Sets PermitEmptyPasswords to no. This disables to use of empty passwords.
          - regexp: "^PermitEmptyPasswords\ "
            line: "PermitEmptyPasswords no"
          
          # Enables Strictmode. This enables checks on the daemon before starting up SSH. For example file permissions. If the settings are wrong. The SSH services does not start.
          - regexp: "^StrictModes\ "
            line: "StrictModes yes"
          
          # Disables multiple RHosts ettings. This disables the use of .rhosts file to connect.
          - regexp: "^IgnoreRhosts\ "
            line: "IgnoreRhosts yes"
          - regexp: "^RhostsAuthentication\ "
            line: "RhostsAuthentication no"
          - regexp: "^RhostsRSAAuthentication\ "
            line: "RhostsRSAAuthentication no"
          
          # Sets ClientAlive settings. Drops idle connections after set time.
          - regexp: "^ClientAliveInterval\ "
            line: "ClientAliveInterval 300"
          - regexp: "^ClientAliveCountMax\ "
            line: "ClientAliveCountMax 0"
          
          # Sets AllowTcpForwarding to no. This disables the use of tcp forwarding via SSH.
          - regexp: "^AllowTcpForwarding\ "
            line: "AllowTcpForwarding no"
          
          # Sets X11Forwarding to no. This disables to use of X11 forwarding via SSH.
          - regexp: "^X11Forwarding\ "
            line: "X11Forwarding no"
          
          # Sets optimal cipher suites to use for the connection.
          - regexp: "^KexAlgorithms\ "
            line: "KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
          - regexp: "^Ciphers\ "
            line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
          - regexp: "^MACs\ "
            line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"

      - name: Reload sshd
        service:
          name: sshd
          state: reloaded